import noCountryForOldMenImage from "../../../assets/images/no-country-for-old-men-image.jpg";
import onceUponATimeInHollywoodImage from "../../../assets/images/once-upon-a-time-in-hollywood-image.jpg";
import jawsImage from "../../../assets/images/jaws-image.jpg";
import bulletTrainImage from "../../../assets/images/bullet-train-image.jpg";
import extractionImage from "../../../assets/images/extraction-image.jpg";
import theKingsManImage from "../../../assets/images/the-kingsman-image.jpg";
import theDepartedImage from "../../../assets/images/the-departed-image.jpg";
import fountainOfYouthImage from "../../../assets/images/fountain-of-youth-image.jpg";
import phantomThreadImage from "../../../assets/images/phantom-thread-image.jpg";
import nurembergImage from "../../../assets/images/nuremberg-image.jpg";
import sendHelpImage from "../../../assets/images/send-help-image.jpg";
import projectHailMaryImage from "../../../assets/images/project-hail-mary-image.jpg";
import noCountryForOldMenCover from "../../../assets/images/no-country-for-old-men-cover.jpg";
import onceUponATimeInHollywoodCover from "../../../assets/images/once-upon-a-time-in-hollywood-cover.jpg";
import jawsCover from "../../../assets/images/jaws-cover.jpg";
import theDepartedCover from "../../../assets/images/the-departed-cover.jpg";
import fountainOfYouthCover from "../../../assets/images/fountain-of-youth-cover.jpg";
import phantomThreadCover from "../../../assets/images/phantom-thread-cover.jpg";
import nurembergCover from "../../../assets/images/nuremberg-cover.jpg";
import sendHelpCover from "../../../assets/images/send-help-cover.jpg";
import projectHailMaryCover from "../../../assets/images/project-hail-mary-cover.jpg";

export const reviewsDeFilmes = [
  {
    id: "1",
    title: "No Country For Old Men",
    author: "Jean Lima",
    date: "APR 21, 2026",
    rating: "5",
    duration: "122 mins",
    director: "Ethan Coen & Joel Coen",
    synopsis: "Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail. The roles of prey and predator blur as the violent pursuit of money and justice collide.",
    trailerURL: "https://www.youtube.com/embed/38A__WT3-o0?si=AQxh8lozS1elTNqb",
    imageURL: noCountryForOldMenImage,
    coverURL: noCountryForOldMenCover,
    summary: "No musics, just the violence of a place without any honor.",
    subtitle: "An Action Masterpiece",
    text: "<p>Texto e bla bla bla</p> <p>Texto e bla bla bla</p> <p>Texto e bla bla bla</p>"
  },
  {
    id: "2",
    title: "No Country For Old Men",
    author: "Jean Lima",
    date: "APR 21, 2026",
    rating: "5",
    duration: "122 mins",
    director: "Ethan Coen & Joel Coen",
    synopsis: "Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail. The roles of prey and predator blur as the violent pursuit of money and justice collide.",
    trailerURL: "https://youtu.be/38A__WT3-o0?si=0FHhglEXw6OlQxne",
    imageURL: noCountryForOldMenImage,
    coverURL: noCountryForOldMenCover,
    summary: "No musics, just the violence of a place without any honor.",
    subtitle: "An Action Masterpiece",
    text: "Uma verdadeira aula de direção. A decisão de remover quase completamente a trilha sonora cria uma tensão atmosférica absurda. A atuação impecável constrói um dos antagonistas mais assustadores e metódicos da história do cinema, refletindo temas profundos sobre a inevitabilidade e o acaso.",
  },
  {
    id: "3",
    title: "No Country For Old Men",
    author: "Jean Lima",
    date: "APR 21, 2026",
    rating: "5",
    duration: "122 mins",
    director: "Ethan Coen & Joel Coen",
    synopsis: "Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail. The roles of prey and predator blur as the violent pursuit of money and justice collide.",
    trailerURL: "https://youtu.be/38A__WT3-o0?si=0FHhglEXw6OlQxne",
    imageURL: noCountryForOldMenImage,
    coverURL: noCountryForOldMenCover,
    summary: "No musics, just the violence of a place without any honor.",
    subtitle: "Onde os velhos não tem vez",
    text: "Uma verdadeira aula de direção. A decisão de remover quase completamente a trilha sonora cria uma tensão atmosférica absurda. A atuação impecável constrói um dos antagonistas mais assustadores e metódicos da história do cinema, refletindo temas profundos sobre a inevitabilidade e o acaso.",
  },
  {
    id: "4",
    title: "Jaws",
    author: "Jean Lima",
    date: "MAY 4, 2026",
    rating: "4",
    duration: "124 mins",
    director: "Steven Spielberg",
    synopsis: "When the seaside community of Amity finds itself under attack by a dangerous great white shark, the town’s chief of police, a young marine biologist, and a grizzled shark hunter embark on a desperate quest to kill the beast before it strikes again.",
    trailerURL: "https://www.youtube.com/embed/sz6rcIZRYLc?si=us8hVvNpXrShbTpn",
    imageURL: jawsImage,
    coverURL: jawsCover,
    summary: "An absolute masterpiece of suspense.",
    subtitle: "SHARKS!",
    text: "<p>Similar with 'Once Upon A Time In Hollywood', it's my second time watching this film, but it's like the first, because the real first time was a long time ago. I was expecting it to be boring or very slow, and I was completely surprised by a very good film that kept me totally interested by from beginning to end. </p> <p>I knew that it was a good movie even if I thought that it was slow, and I knew its importance for cinema and for Spielberg. Even so, I was expecting something more boring and slow, and it wasn't.</p> <p>I really love the vibe of both parts of the movie, the first in the city with the police trying to solve the situation, and the second with the trio trying to hunt the shark. It's not scary in nowadays but it's very fun. </p> <p>PS: Is really impressive watch the backstages and figure how Spielberg made this classic in the era of practical effects. By the way, this era is sorely missed, most of films today are stuffed with CGI, giving that look of artificial. </p>",
  },
  {
    id: "5",
    title: "Once Upon a Time In Hollywood",
    author: "Jean Lima",
    date: "MAY 5, 2026",
    rating: "4",
    duration: "162 mins",
    director: "Ethan Coen & Joel Coen",
    synopsis: "Llewelyn Moss stumbles upon dead bodies, $2 million and a hoard of heroin in a Texas desert, but methodical killer Anton Chigurh comes looking for it, with local sheriff Ed Tom Bell hot on his trail. The roles of prey and predator blur as the violent pursuit of money and justice collide.",
    trailerURL: "https://youtu.be/38A__WT3-o0?si=0FHhglEXw6OlQxne",
    imageURL: onceUponATimeInHollywoodImage,
    coverURL: onceUponATimeInHollywoodCover,
    summary: "No musics, just the violence of a place without any honor.",
    subtitle: "Onde os velhos não tem vez",
    text: "Uma verdadeira aula de direção. A decisão de remover quase completamente a trilha sonora cria uma tensão atmosférica absurda. A atuação impecável constrói um dos antagonistas mais assustadores e metódicos da história do cinema, refletindo temas profundos sobre a inevitabilidade e o acaso.",
  },
  {
    id: "6",
    title: "Jaws",
    author: "Jean Lima",
    date: "MAY 6, 2026",
    rating: "4",
    duration: "124 mins",
    director: "Steven Spielberg",
    synopsis: "When the seaside community of Amity finds itself under attack by a dangerous great white shark, the town’s chief of police, a young marine biologist, and a grizzled shark hunter embark on a desperate quest to kill the beast before it strikes again.",
    trailerURL: "https://www.youtube.com/embed/sz6rcIZRYLc?si=us8hVvNpXrShbTpn",
    imageURL: jawsImage,
    coverURL: jawsCover,
    summary: "An absolute masterpiece of suspense.",
    subtitle: "SHARKS!",
    text: "<p>Similar with 'Once Upon A Time In Hollywood', it's my second time watching this film, but it's like the first, because the real first time was a long time ago. I was expecting it to be boring or very slow, and I was completely surprised by a very good film that kept me totally interested by from beginning to end. </p> <p>I knew that it was a good movie even if I thought that it was slow, and I knew its importance for cinema and for Spielberg. Even so, I was expecting something more boring and slow, and it wasn't.</p> <p>I really love the vibe of both parts of the movie, the first in the city with the police trying to solve the situation, and the second with the trio trying to hunt the shark. It's not scary in nowadays but it's very fun. </p> <p>PS: Is really impressive watch the backstages and figure how Spielberg made this classic in the era of practical effects. By the way, this era is sorely missed, most of films today are stuffed with CGI, giving that look of artificial. </p>",
  },
  {
    id: "7",
    title: "The Departed",
    author: "Jean Lima",
    date: "MAY 7, 2026",
    rating: "4.5",
    duration: "151 mins",
    director: "Martin Scorcese",
    synopsis: "To take down South Boston’s Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks. But both sides soon discover there’s a mole among them.",
    trailerURL: "https://www.youtube.com/embed/r-MiSNsCdQ4?si=03P7EoLCJh-LGFIg",
    imageURL: theDepartedImage,
    coverURL: theDepartedCover,
    summary: "That death in the ending is really surprising.",
    subtitle: "Don't trust in anyone",
    text: "<p>This is my second time watching 'The Departed', but like other movies, actually is the first, because I've slept most of the film on the first attempt. </p> <p>I love movies with this 'liar theme', where a character tries to impersonate someone, while execute a big plan, just like 'Blackkklansman' and 'The Talented Ripley'. I don't know exactly why, but this kind of thing can really be tense and fun for me. </p> <p>And this movie is a masterpiece of the genre. With two simultaneous infiltrators trying not to be discovered while they give information about the other side. This battle of liars, while we hope one get caught and the other doesn´t is really good and remind me of my favorite anime ever 'Death Note'. </p> <p>I'm not really inspired to write today, but is this. I love this film, and this dynamics of both trying to catch each other and every single detail being important in this hunt. All of this happening while identity and the fine line of good evil is put to the test. </p> <p>PS: And that sequence of twists in the ending is really interesting to show that even us know what is really happening. </p>",
  },
  {
    id: "8",
    title: "Fountain Of Youth",
    author: "Jean Lima",
    date: "MAY 8, 2026",
    rating: "2",
    duration: "126 mins",
    director: "Guy Ritchie",
    synopsis: "A treasure-hunting mastermind assembles a team for a life-changing adventure. But to outwit and outrun threats at every turn, he’ll need someone even smarter than he is: his estranged sister.",
    trailerURL: "https://www.youtube.com/embed/1gB9h0ELEf0?si=gTi112oX75rmmlha",
    imageURL: fountainOfYouthImage,
    coverURL: fountainOfYouthCover,
    summary: "What happened with you, Guy Ritchie? ",
    subtitle: "Is this really a movie?",
    text: "<p>To start, I can talk about my relation with Guy Ritchie and how I hope the best to him. He was one of the first directors that I've recorded the name. Me and my brother have known Ritchie in the very beggining of our cinema road by the movie 'The Gentlemen' (near 2020) and he got our atention and since then we've watched all his releases and his best old movies (almost all cinematography).</p> <p>We've watched some movies made by him before - like Sherlock Holmes and King Arthur - but at this time, we were just watching movies. </p> <p>I love 'The Man From U.N.C.L.E' (it's one the films I've watched the most), 'Snatch' and 'The Gentlemen'. I also like both Sherlock Holmes' movies and other classics like'Lock Stock and Two Smoking Barrels and Revolver'.</p> <p>And even bad but fun movies like 'Wrath of Man', 'King Arthur' and 'The Ministry of Ungentlemanly Warfare'. But in the few last years the level of his projects are clearly falling and movies like 'Operation Fortune' and 'Fountain of Youth' make me if we really need new Guy Ritchie's movies. </p> <p>I don't have much to talk about this movie, it's just soulless. The acting, script, direction, everything is nothing. Nothing is insteresting, fun or cool. It's a film but doesn't seem like one. </p> <p>PS: I hate kids solving hard problems in movies. And even I've said, I'll still watching Ritchie's movies. </p>",
  },
  {
    id: "9",
    title: "Phantom Thread",
    author: "Jean Lima",
    date: "MAY 11, 2026",
    rating: "4.5",
    duration: "130 mins",
    director: "Paul Thomas Anderson",
    synopsis: "In 1950s London, a renowned dressmaker’s meticulous lifestyle begins drastically changing as his relationship with his young muse intensifies.",
    trailerURL: "https://www.youtube.com/embed/xNsiQMeSvMk?si=vRg0eYswJlpbQnpk",
    imageURL: phantomThreadImage,
    coverURL: phantomThreadCover,
    summary: "I need time to process this movie. And revisit one day. ",
    subtitle: "I'm not old enough",
    text: "<p>Another movie about obssesion! I'm actually trying to risk all the obssession movies from that video that I said in the next days. </p> <p>And this movie was automatically to the 'need to revisit list'. This movie is so good and so complex, with a lot of little details and things to think about, that almost one day with it in my mind wasn't enough to have much to say here. And as I was watching, I realized that it is that kind of movie that I'm not old enough to full undestand it, I need to live at least a few more years to have a start point. </p> <p>I've watched it almost without information about it, which is a little rare in nowadays, because I live in this cinema world and most of times I start a movie having already seen it a trailer, a scene, the synopsis, etc. And have this experience with pure ignorance was excellent. I actually don't know why I've never heard about this movie, it's really really good. </p> <p>And with the little I knew about it, I was expecting something different and a different kind of obssesion. And this kind of obssesion and the way that was made is awesome! </p> <p>PS: I'll try to watch PTA's filmography in next weeks also. </p>",
  },
  {
    id: "10",
    title: "Nuremberg",
    author: "Jean Lima",
    date: "MAY 12, 2026",
    rating: "2.5",
    duration: "149 mins",
    director: "James Vanderbilt",
    synopsis: "In postwar Germany, an American psychiatrist must determine whether Nazi prisoners are fit to go on trial for war crimes, and finds himself in a complex battle of intellect and ethics with Hermann Göring, Hitler’s right-hand man.",
    trailerURL: "https://www.youtube.com/embed/WvAy9C-bipY?si=8SJPH9XE8Je81tRN",
    imageURL: nurembergImage,
    coverURL: nurembergCover,
    summary: "A great premise, a bad movie.",
    subtitle: "Out of tune",
    text: "<p>Again, I've watched this film completely blind. And even more blind than usual, because I've no ideia about this facts and the true history. </p> <p>So, when I undestood what the movie would be about and the duration of more than 2 hours, I got really excited to see to which way the movie would go. And at that point, I remeber to thout: 'This is a very complex and interesting theme. It'll need a very good script to make it worthy of the true story'. </p> <p>And maybe the script is not the biggest problem (even it's a big problem), but the direction. I don't know exactly why, but this movie looks like it's in the wrong vibe and tone. It's really strange to see that real footage from Holocaust and see the tone of the scenes before and after. It looks like a superhero movie or an action movie. Which is very strange to Holocaust film. Looks like it wants to be a cool movie, with the protagonist doing magic tricks and smoking. </p> <p>After watch it, I went search for the director and writer and it was really surprising. James Vanderbilt is a person that can write 'Zodiac' - for me, one of the top 100 movies of the century - and 'Fountain of Youth', 'White House Down', 'Murder Mistery' - very bad movies. And it's just his second movie as director. I think he has potential, but has a lot to learn and it's funny how inconsistent he is. </p> <p>The movie is minimum well made, it looks like a movie and have some good acting, scenes and ideias (like these scenes of the existence of nazi's in EUA and the ideia to try to avoid a new Holocaust), but it's not even close from what it could be. Potential totally wasted. </p> <p>One thing that make me happy is to think all these things about this movie and think that just a few years ago (maybe even months) I would think that this movie is good or even very good. It's really pleasant to see that watch a lot of movies, review a lot of movies, see expert people talking about movies or just get older are changing my taste, my analisys and my way to see art pieces. This year I'm trying to read more books and play more games and I can perceive that I have no opinion or just think that everything is good, because I still don't have a wide collection of games and books in my mind. </p> <p>And I'm really excited to learn about these kind of art and start to recognize this good and bad things. </p> <p>This good feeling just get better when I realized that I've watched 'The Lady From Shanghai' before watch 'Nuremberg' and I didn't get bored with a 1947 film and undestood why it's so good. Obviously, I just scratched the surface of understanding and I've a lot to learn and maturing, but see this evolution is really awesome.</p> <p>PS: I'll try to watch 'Judgment at Nuremberg (1961)' to check if it's better. </p>",
  },
  {
    id: "11",
    title: "Send Help",
    author: "Jean Lima",
    date: "MAY 14, 2026",
    rating: "3",
    duration: "113 mins",
    director: "Sam Raimi",
    synopsis: "Two colleagues become stranded on a deserted island, the only survivors of a plane crash. On the island, they must overcome past grievances and work together to survive, but ultimately, it’s a battle of wills and wits to make it out alive.",
    trailerURL: "https://www.youtube.com/embed/R4wiXj9NmEE?si=nLJzMCiwrxxfjFcs",
    imageURL: sendHelpImage,
    coverURL: sendHelpCover,
    summary: "A good premise, a predictable movie. ",
    subtitle: "Maybe my fault",
    text: "<p>My review to this one is very short. It's not a bad movie, it's just predictable. </p> <p>This medium experience was probably my fault, to become exigent with movies or to expect more from a new Sam Raimi's movie. It's just a okay movie, that in another times I would give a 3.5 or 4 stars. But yesterday when I saw almost all the things coming wasn't a good experience. </p> <p>I think that if it was just a little better and surprising, it could be a good movie for me. But seeing the reviews, most of the people liked and maybe this time it wasn't Raimi fault, but mine. </p> <p>But another thing about this movie that I saw a video about last year, is how the movies are getting dumber and shallow. This new era where the people 'watch' the movie while scroll on phone - I put it in quotation marks because I don't think this is truly watch something - or just can't undestand or like something when it's a little bit complex is creating dumb and shallow movies and vice-versa. </p> <p>And I felt this watching this film. I felt like everything is super straight without anything more than the necessary. And I know that every scene must have a reason, but I felt like it should have more scenes. </p> <p>I don't know. Maybe it's a good movie. But for me, was a bad experience. </p>",
  },
  {
    id: "12",
    title: "Project Hail Mary",
    author: "Jean Lima",
    date: "MAY 15, 2026",
    rating: "4.5",
    duration: "156 mins",
    director: "Phil Lord & Christopher Miller",
    synopsis: "Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction… but an unexpected friendship means he may not have to do it alone.",
    trailerURL: "https://www.youtube.com/embed/m08TxIsFTRI?si=ENob35Jm9MVxk2fn",
    imageURL: projectHailMaryImage,
    coverURL: projectHailMaryCover,
    summary: "A cozy space adventure.",
    subtitle: "Fun space movie",
    text: "<p>To begin with, I need to say this film is a very good surprise for me. Even watching the trailer and knowing the people involved in the project and knowing how good they are, I wasn't expecting a film so good. This is my new 'The Martian' - a film that I love and revisit every year to feel that good vibe of a space adventure. By the way, the brazillian version of 'Starman' is my brazillian favorite music. </p> <p>There are some kind of movies that I think that deserves a new movie every year and a cozy space adventure is one of them. It's so good to just be in this good vibe for 2 hours. </p> <p>And for me, this is the big thing of the movie. I didn't laugh at most of the jokes and I didn't cry at the sad scenes, but this good feeling of comfort and carefree by a man and his rock friend trying to save their respective worlds for 2 hours is really delightful. </p> <p>And is this. I don't have so much to talk about this movie, just watch it, please. </p> <p>PS: Another good point is how beautiful this movie is. I need to revisit it in 4k. </p>",
  },
];
